os:
  - linux
  - osx
language: node_js
node_js:
  - '8'

install:
  - yarn

script: yarn run test

# Submit Coverage Status to coveralls.io
after_script:
  - cat ./src/test/js/unit/coverage/lcov.info
  - cat ./src/test/js/unit/coverage/lcov.info | ./node_modules/.bin/coveralls
